[build-system]
requires = ["setuptools >= 64", "setuptools_scm >= 8"]
build-backend = "setuptools.build_meta"

[project]
name = "atmos"
description = "symlink-based layering of directories"
readme = "README.md"
authors = [
    { name = "Jens G Magnus", email = "atmosrepo.ensure573@passinbox.com" }
]
license = { file = "LICENSE" }
requires-python = ">= 3.8"
keywords = []
dependencies = [
    "diskcache",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/jensgm/atmos"

[project.scripts]
atmos = "atmos.cli:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "sphinx",
]

[tool.setuptools_scm]
write_to = "atmos/version.py"

[tool.pytest.ini_options]
addopts = "-ra --strict-markers"
